server:
  port: 8080

spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://immediate-meetup-database.c8voaqaignj7.ap-northeast-2.rds.amazonaws.com/Immediate_Meetup_Server_RDS
    # url ??? jdbc:mysql://RDS? EndPoint/?? DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: meetup1234

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        show_sql: true